/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PruebasFicheros;


public class App {
    

    public static void main(String[] args) {
        //PruebaFicheros.pruebaFOS("/home/jorge/", "ivan.bin");
        //PruebaFicheros.pruebaFIS("/home/jorge/ivan.bin");
        //PruebaFicheros.pruebaBOS("/home/jorge/ivan.bin");
        //PruebaFicheros.pruebaBIS("/home/jorge/ivan.bin");
        //PruebaFicheros.pruebaDOS("/home/jorge/ejercicio8.bin");
        
        
    //Ejercicio 9
        //PruebaFicheros.pruebaFIS("/home/jorge/ejercicio8.bin");
        //PruebaFicheros.pruebaBIS("/home/jorge/ejercicio8.bin");
        
    //Ejercicio 10    
        //PruebaFicheros.pruebaDIS("/home/jorge/ejercicio8.bin");
    
    //Ejercicio 11
        //PruebaFicheros.pruebaByteOS("/home/jorge/ejercicio11.bin");
    
    //Ejercicio 12    
        //PruebaFicheros.pruebaByteIS("/home/jorge/ejercicio11.bin");
        
    //Ejercicio 13
        //PruebaFicheros.pruebaPrint("/home/jorge/ejercicio13.bin");
        //PruebaFicheros.pruebaPrint();
        
    //Ejercicio 14
        //PruebaFicheros.pruebaSequence("/home/jorge/ejercicio13.bin", "/home/jorge/ejercicio11.bin");
    
    //Ejercicio 15
        //PruebaFicheros.testFW("/home/jorge/ejercicio15.txt");
        
    //Ejercicio 16
        //PruebaFicheros.testFW("/home/jorge/ejercicio16.txt", "Mi primer fichero de texto en Java");
    
    //Ejercicio 17
        //PruebaFicheros.testFR("/home/jorge/ejercicio18.txt");
        
    //Ejercicio 18
        //PruebaFicheros.testBW("/home/jorge/ejercicio18.txt");
        
    //Ejercicio 19
        //PruebaFicheros.testBR("/home/jorge/ejercicio18.txt", "Lectura simple");
        
    //Ejercicio 21
        //PruebaFicheros.testCAW("/home/jorge/ejercicio21.txt");
        
    //Ejercicio 24
        //PruebaFicheros.testLNR("/home/jorge/ejercicio24.txt");
        
    //Ejercicio 25
        //se abre un fichero, se lee en el buffer, el stringWriter almacena cada posicion del array 
    
    //Ejercicio 26
        //PruebaFicheros.testSR("/home/jorge/ejercicio24.txt");
    
    
    }
}
